### ISSUE TITLE
low frequency of fovis

### ISSUE THREAD

**Issue by LiliMeng** [srv/libfovis#11]
Hi,
         The fovis_ros publishes at a very low frequency, 2-3hz. We have the same problem as https://github.com/srv/fovis/issues/7

```
       Any suggestions? Thanks a lot!
```

**Comment by tomassykora** [comment]
Hi, 
I'm facing the same problem with the low frequency. Did you solve it somehow?

**Comment by miquelmassot** [comment]
Hi @LiliMeng and @tomassykora, can you check if your messages are synchronized? Create a publisher inside imageCallback (https://github.com/srv/fovis/blob/indigo/fovis_ros/src/mono_depth_odometer.cpp#L55) and check its frequency.

**Comment by tomassykora** [comment]
Hi @miquelmassot, thanks for the answer. I put a publisher inside this function and its frequency is the same as the frequency of odometry messages. Btw. what is the expected frequency of the published odometry anyway? I adjusted the bucketing params a little bit and got 5-6Hz but it's probably on the expense of worse quality of the odometry.

**Comment by miquelmassot** [comment]
Then there's an issue, your input topics are hard to synchronise. How many frames per second do you have in your input topic? Can you also try to set up the param

    <param name="approximate_sync" type="bool" value="True" />

in fovis launch?

**Comment by tomassykora** [comment]
I just noticed that the problem may come from another package (pointcloud_to_laserscan). If I stop this package and just openni2_launch node remains running (with fovis), the odometry messages frequency is around 14Hz. I'm still not sure if it is the right frequency, that's why I was asking what is the expected one. 

And to your questions, the input topic have pretty high frequency, around 50Hz and I was already using the approximate_sync param.

**Comment by miquelmassot** [comment]
If there is enough computing power, you should have odometry at the same frequency as the input topic.

**Comment by tomassykora** [comment]
So I have to determine now whether it is a performance problem or not. I don't have any high performance pc, just core i5, 2.5MHz, but I think it should handle this one running node without loosing so much frequency, shouldn't it?

**Comment by miquelmassot** [comment]
I don't know what else you have running at the same time. Use htop to check if your CPU is free or not.

**Comment by tomassykora** [comment]
It seems I found what's the issue. I was building my workspace with just catkin_make. When I built it with catkin_make -DCMAKE_BUILD_TYPE=Release, the odometry frequency of fovis is the same as input topic. Thank you for your time.

**Comment by miquelmassot** [comment]
Summary:
 - Build with `catkin_make -DCMAKE_BUILD_TYPE=Release`
 - Use `<param name="approximate_sync" type="bool" value="True" />`
 - Free the computer from the burden of another ros packages such as _pointcloud_to_laserscan_
