### ISSUE TITLE
Empty Debian package due to missing install targets

### ISSUE THREAD

**Issue by cdondrup** [srv/libfovis#5]
Sadly, there are no install targets defined in the CMakeLists.txt which results in a debian package `ros-hydro-libfovis` (I'm using hydro but here are no install targets for groovy and indigo either) that builds perfectly but does not install anything. This is what is installed after running `sudo apt-get install ros-hydro-libfovis`:

``` bash
cdondrup@calculon:/opt/ros/hydro
$ find . -iname "*fovis*"
./lib/pkgconfig/libfovis.pc
./share/libfovis
./share/libfovis/cmake/libfovisConfig.cmake
./share/libfovis/cmake/libfovisConfig-version.cmake
cdondrup@calculon:/opt/ros/hydro
$ lr share/libfovis/
share/libfovis/:
total 24K
drwxr-xr-x   3 root root 4.0K Oct  1 10:49 .
drwxr-xr-x 301 root root  12K Oct  1 11:13 ..
drwxr-xr-x   2 root root 4.0K Oct  1 10:49 cmake
-rw-r--r--   1 root root  612 Feb  5  2014 package.xml

share/libfovis/cmake:
total 20K
drwxr-xr-x 2 root root 4.0K Oct  1 10:49 .
drwxr-xr-x 3 root root 4.0K Oct  1 10:49 ..
-rw-r--r-- 1 root root 7.2K Aug 19 18:41 libfovisConfig.cmake
-rw-r--r-- 1 root root  426 Aug 19 18:41 libfovisConfig-version.cmake
cdondrup@calculon:/opt/ros/hydro
$ cat ./lib/pkgconfig/libfovis.pc
prefix=/opt/ros/hydro

Name: libfovis
Description: Description of libfovis
Version: 0.0.4
Cflags: -I/opt/ros/hydro/include
Libs: -L/opt/ros/hydro/lib -llibfovis
Requires: 
cdondrup@calculon:/opt/ros/hydro
$ ls /opt/ros/hydro/include/*fovis*
ls: cannot access /opt/ros/hydro/include/*fovis*: No such file or directory
cdondrup@calculon:/opt/ros/hydro
$ ls /opt/ros/hydro/lib/*fovis*
ls: cannot access /opt/ros/hydro/lib/*fovis*: No such file or directory
```

This shows that a pkg-config file is created but it points to non-existing directories. This results in packages relying on libfovis to not build, like

``` bash
-- +++ processing catkin package: 'fovis_ros'
-- ==> add_subdirectory(fovis/fovis_ros)
CMake Error at /opt/ros/hydro/share/libfovis/cmake/libfovisConfig.cmake:141 (message):
  Project 'fovis_ros' tried to find library 'libfovis'.  The library is
  neither a target nor built/installed properly.  Did you compile project
  'libfovis'? Did you find_package() it before the subdirectory containing
  its code is included?
Call Stack (most recent call first):
  /opt/ros/hydro/share/catkin/cmake/catkinConfig.cmake:75 (find_package)
  fovis/fovis_ros/CMakeLists.txt:4 (find_package)


-- Configuring incomplete, errors occurred!
```

 and makes it therefore useless as a debian package.

Are there any plans on adding install targets: http://wiki.ros.org/catkin/CMakeLists.txt (10. Optional Step: Specifying Installable Targets)? If there is no one actively working on this, I can also create install targets and open a pull request because I would really like to be able to use this.

**Comment by plnegre** [comment]
Any pull request will be welcome! We have a lot of ros packages to mantain and not enough time for it :(

If you make just one pull request for hydro, for example, then we will merge it over all branches and generate the bloom as well.

Thank you very much in advance.

**Comment by cdondrup** [comment]
I will try to do this asap.
Thank you for your help!

**Comment by cdondrup** [comment]
Would it be possible to do the same for hydro and groovy as well?

**Comment by miquelmassot** [comment]
I think @plnegre is doing it. As groovy is EOL I don't recommend upgrading
the repo, but hydro changes have been done already.

2014-10-02 12:13 GMT+02:00 Christian Dondrup notifications@github.com:

> Would it be possible to do the same for hydro and groovy as well?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/srv/libfovis/issues/5#issuecomment-57608667.

## 

Miquel Massot

miquel.massot@gmail.com      http://www.facebook.com/massot
http://www.twitter.com/resisteix http://gplus.to/massot

**Comment by cdondrup** [comment]
Thank you very much for your help!

**Comment by LiliMeng** [comment]
@Miquel Thanks a lot! I have already installed the ros_hydro_libfovis, but
the fovis still cannot find the libfovis.

On Tue, Oct 28, 2014 at 1:54 AM, Miquel Massot notifications@github.com
wrote:

> @LiliMeng https://github.com/LiliMeng have you installed
> ros_hydro_libfovis ?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/srv/libfovis/issues/5#issuecomment-60725406.

## 

Best Regards,

Lili Meng

PhD Candidate
Industrial Automation Lab
Department of Mechanical Engineering
University of British Columbia

**Comment by cdondrup** [comment]
Are the changes made in 5e3bcfb6d026d870f9cd9de979ad431cf7d7f73c already in the current release version?

**Comment by LiliMeng** [comment]
Thanks a lot! At first, I used $sudo apt-get install ros-hydro-libfovis,
the fovis cannot find libfovis. But after your suggestion, I downloaded the
libfovis-hydro package and compiled it. It's successful now!:)

On Tue, Oct 28, 2014 at 10:18 AM, Christian Dondrup <
notifications@github.com> wrote:

> Are the changes made in 5e3bcfb
> https://github.com/srv/libfovis/commit/5e3bcfb6d026d870f9cd9de979ad431cf7d7f73c
> already in the current release version?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/srv/libfovis/issues/5#issuecomment-60794482.

## 

Best Regards,

Lili Meng

PhD Candidate
Industrial Automation Lab
Department of Mechanical Engineering
University of British Columbia
