### ISSUE TITLE
Compile problem of Fovis

### ISSUE THREAD

**Issue by LiliMeng** [srv/libfovis#8]
Hi, I run $catkin_make for fovis, but it has the following errors, could someone provide some suggestions? Thanks in advance! 

CMake Error at /opt/ros/hydro/share/catkin/cmake/catkinConfig.cmake:75 (find_package):
  Could not find a configuration file for package libfovis.

  Set libfovis_DIR to the directory containing a CMake configuration file for
  libfovis.  The file will have one of the following names:

```
libfovisConfig.cmake
libfovis-config.cmake
```

**Comment by miquelmassot** [comment]
@LiliMeng have you installed ros-hydro-libfovis ?

**Comment by plnegre** [comment]
@LiliMeng the latest version of libfovis release is not yet available for direct installation (apt-get install ros-indigo-libfovis). On the meanwhile download and compile https://github.com/srv/libfovis directly.
