### ISSUE TITLE
How to use libfovis for stereo camera such as Bumblebee

### ISSUE THREAD

**Issue by symao** [srv/libfovis#9]
I use processFrame() in VisualOdometry class to add image(left) and stereoSource which contain right image.But the matching status is always 4 which means large reproject error.

Is there any sample code for stereo camera fovis? I only see the depth camera sample code.

**Comment by miquelmassot** [comment]
See https://github.com/srv/fovis

**Comment by symao** [comment]
Hi @miquelmassot 
Thanks for your reply. I write my stereo odometry just like the fovis_ros stereo_odometer.cpp. I can compile my code, but it failed once i run. The error is:
"Assertion failed: FOVIS_IS_ALIGNED16(a) && FOVIS_IS_ALIGNED16(b), file ...\fovis\refine_feature_match.cpp, line 25".
Do you know what's wrong?

Here is my code:
//==============================================//

```
    fovis::CameraIntrinsicsParameters cameraParams(640,480,517.3,516.5,318.6,255.3);
fovis::Rectification rect(cameraParams);
fovis::VisualOdometryOptions options = getDefaultOptions();
fovis::VisualOdometry* odom = new fovis::VisualOdometry(&rect, options); // setup the visual odometry

fovis::StereoCalibrationParameters stereoParams;
stereoParams.left_parameters = stereoParams.right_parameters = cameraParams;
stereoParams.right_to_left_rotation[0] = 1;
stereoParams.right_to_left_rotation[1] = 0;
stereoParams.right_to_left_rotation[2] = stereoParams.right_to_left_rotation[3] = 0;
stereoParams.right_to_left_translation[0] = -0.12;
stereoParams.right_to_left_translation[1] = 0;
stereoParams.right_to_left_translation[2] = 0;
fovis::StereoCalibration stereoCalib(stereoParams);
fovis::StereoDepth* depth = new fovis::StereoDepth(&stereoCalib,options);

cv::Mat img_left,img_right;
for(int i=1;i<100;i++)
{
    img_left = cv::imread(data_dir+"l"+num2str(i)+".jpg",cv::IMREAD_GRAYSCALE);
    img_right = cv::imread(data_dir+"r"+num2str(i)+".jpg",cv::IMREAD_GRAYSCALE);

    depth->setRightImage(img_right.data);
    odom->processFrame(img_left.data,depth);
    cout<<odom->getMotionEstimateStatus()<<endl;
}
```

//==============================================//
Note that I am build my code in vs2008,windows 64bit and i build fovis code from source.

**Comment by miquelmassot** [comment]
Hi @symao, 

we are not maintainers of libfovis, we just wrote a wrapper of it in [ROS](http://www.ros.org/). For issues related to the main library I encourage you to [contact their developers](https://code.google.com/p/fovis/). 

In our case, we are using 1 channel 8 bit images (unsigned char). Check that your datatypes are the same.
